### ISSUE TITLE
Time for proposals

### ISSUE THREAD

**Issue by jzaefferer** [jquery/gsoc#1]
If you're a student watching this repo and interested in working on one of our projects for GSoC 2015: You should start writing a proposal! You can [submit proposals](https://www.google-melange.com/gsoc/homepage/google/gsoc2015) starting Monday, 16th of March to the 27th of March. You're welcome to share drafts with mentors to get feedback and improve your proposal.

As examples, here's two drafts that look promising:

UI demo system: https://gist.github.com/tanay1337/484daa8bb8410bcb607a
QUnit diff: https://gist.github.com/gauravmittal1995/289e80ee588a7404b997

Feel free to use this issue for any proposal-related questions.

**Comment by ikeshek** [comment]
alright .. how can I submit a proposal for one of the projects?

**Comment by jzaefferer** [comment]
Use the official GSoC site: https://www.google-melange.com/gsoc/homepage/google/gsoc2015

**Comment by ikeshek** [comment]
Do I have to discuss  a new idea to propose ... or I can work on an existing idea?

**Comment by jzaefferer** [comment]
At this point you should contact a mentor before proposing something, since we're pretty close to the deadline (27th, Friday) and proposing something that has been submitted multiple times already would likely be a waste of time. Applies both to ideas on the our list and anything outside of that.

**Comment by jzaefferer** [comment]
The deadline is 27th, 19:00 UTC. If you haven't submitted, yet, now's the time.
