### ISSUE TITLE
gsoc Website

### ISSUE THREAD

**Issue by manishbisht** [jquery/gsoc#4]
Hello Everyone,

I want to make some contributions on jQuery. So I have one idea can we make the official website of the GSOC 2016 like on the domain gsoc16.jquery.org or the other domain you like. On that page all the details related to mentors and ideas will be put there and we can write there some useful tips for the students to get selected in GSOC 2016.
It will be very useful for the students and also we as the jquery contributor have some place where all the details of the mentor and students can be kept.

Hope you all will like this.

Thanks :)

**Comment by iamonuwa** [comment]
Hello Devs,

Am Isaac from Nigeria. I have been using jQuery Mobile to build applications. I would like to use this GSoC opportunity to build a better idea with my experience in jQuery Mobile.

**Comment by arschmitz** [comment]
Hi This is not the place for these sort of questions please contact one of the mentors for the projects you are interested in. The best way to do this is on irc
