### ISSUE TITLE
Not all mentors have correct link to their details

### ISSUE THREAD

**Issue by karooolis** [jquery/gsoc#5]
Hi there,

I am interested why only some of the projects but not all have 'proper' links for while others link to https://github.com/jquery/gsoc/wiki. Is it left like that on purpose?

**Comment by aulvi** [comment]
Could you provide an example of a working and non-working link? Thanks!

**Comment by arschmitz** [comment]
it looks like many of the dojo mentors have bad profile links ill ping them

**Comment by karooolis** [comment]
As an example, John-David Dalton profile goes to https://github.com/jquery/gsoc/wiki which seems like it might be unintentional while link for Chris Thoburn goes to his GitHub profile at https://github.com/runspired.

**Comment by aulvi** [comment]
@ramkarolis Yeah, most likely unintentional.

@arschmitz Thanks for being the messenger!

**Comment by aulvi** [comment]
@ramkarolis Okay, I've corrected the links. Thanks for the heads-up!
